version: '3.8'

services:
  minetrack:
    image: verycooldocker/minetrack:latest
    build: .
    container_name: minetrack
    environment:
      SITE_PORT: 8080
      LOG_TO_DATABASE: "false"
      DB_TYPE: sqlite
      SQLITE_FILENAME: /data/database.sql
      ALLOWED_ORIGINS: http://localhost:8080
      SERVERS_JSON: '[{"name":"Hypixel","ip":"mc.hypixel.net","type":"PC"}]'
    ports:
      - "8080:8080"
    volumes:
      - minetrack_data:/data
    restart: unless-stopped

volumes:
  minetrack_data:
